### ISSUE TITLE
代码生成

### ISSUE THREAD

**Issue by llh4github** [llh4github/ordinary-admin-web#12]
## 配置
```yml
code-gen-properties:
    auth: llh
    table-prefix: a_
    # 忽略字段。用于忽略公共的字段属性，用在查询时生成not in (xx)语句
    ignore-fields: id,create_at 
    # 用于mysql与ktorm框架类型映射。
    # 仅列出常用的类型
    # 统一使用大写，方便进行比较
    # mysql中Boolean的规范为TINYINT(1)，需要添加额外的判断
    type-map:
        TINYINT: Int
        SMALLINT: Int
        MEDIUMINT: Int
        INT: Int
        INTEGER: Int
        BIGINT: Long
        FLOAT: Float
        DOUBLE: Double
        DECIMAL: java.math.BigDecimal

        CHAR: String
        TINYTEXT: String
        tinytext: String
        TEXT: String
        MEDIUMTEXT: String
        LONGTEXT: String

        DATE: java.time.LocalDate
        TIME: java.time.LocalTime
        YEAR: Int
        DATETIME: java.time.LocalDateTime
        TIMESTAMP: java.time.LocalDateTime
```
## 配置类
```java
@Component
@ConfigurationProperties(prefix = "code-gen-properties")
@Data
public class CodeGenProperties {
    private Map<String, String> typeMap = new HashMap<>();
    private String auth;
    private String tablePrefix;
    private String ignoreFields;
}
```
